In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import os
import matplotlib.pyplot as plt

In [2]:
with open(os.getcwd()+'\\data\\input.txt', 'r', encoding='utf8') as f:
    text = f.read()

In [2]:
torch.cuda.is_available()

True

In [3]:
chars = sorted(list(set(text)))

vocab_size = len(chars)

print(''.join(chars))
print(vocab_size)

#strategy to tokenize text

#character level mapping

s_to_i = {ch:i for i,ch in enumerate(chars)}
i_to_s = {i:ch for i,ch in enumerate(chars)}

encode = lambda s: [s_to_i[c] for c in s]
decode = lambda l: ''.join([i_to_s[c] for c in l])

print(encode("hii there"))
print(decode(encode("hii there")))

#take all of the text and encode them into pytorch tensors

data = torch.tensor(encode(text), dtype = torch.long)
print(data.shape, data.dtype)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65
[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there
torch.Size([1115394]) torch.int64


In [4]:
#splitting into a train and validation split

n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [5]:
#input the text sequences into the transformer

#we only work with chunks of the dataset. when we train the model, we sample chunks of the dataset and train on just chunks at a time. chunks have a maximum length: called block_size

block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [6]:
x = train_data[:block_size]

#shift to the right by 1 to get the target
y = train_data[1:block_size+1]

In [7]:
for t in range(block_size):
    context = x[:t+1]
    target = y[t]

    print(f"when the input is {context}, the target will be {target}")

#we want the model to be robust when seeing contexts of multiple lengths, we set it as 8 so that the model has the capability of looking back at least 'block_size' characters of contexts of. 
# When we need to predict the 9th or 10th character, we start to truncate the context to continue onwards

when the input is tensor([18]), the target will be 47
when the input is tensor([18, 47]), the target will be 56
when the input is tensor([18, 47, 56]), the target will be 57
when the input is tensor([18, 47, 56, 57]), the target will be 58
when the input is tensor([18, 47, 56, 57, 58]), the target will be 1
when the input is tensor([18, 47, 56, 57, 58,  1]), the target will be 15
when the input is tensor([18, 47, 56, 57, 58,  1, 15]), the target will be 47
when the input is tensor([18, 47, 56, 57, 58,  1, 15, 47]), the target will be 58


In [23]:
#GLOBALS

batch_size = 4 #This is the value of B
block_size = 8 #This is the value of T
n_embd = 32 #This is the value of C
dropout = 0.4
n_layers = 6


In [78]:
#getting the batches
torch.manual_seed(1337)
def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])

    return x, y

xb, yb = get_batch('train')

print('inputs:')
print(xb.shape)
print(xb)
# print('targets:')
print(yb.shape)
print(yb)

#xb, yb, of shape (B, T) where B = batch_size, and T = block_size (time sequence)

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])


transformer time!

head -> multi-head self attention -> feedforward -> block -> Decoder

special layers:
dropout
layernorm
linear
embedding
pos_embedding

In [84]:
class Head(nn.Module):
    """
    One Head of self-attention 
    """
    def __init__(self, head_size):
        super().__init__()

        self.head_size = head_size
        #initialize the key, query, and value matrices
        self.Wk = nn.Linear(n_embd, head_size)
        self.Wq = nn.Linear(n_embd, head_size)
        self.Wv = nn.Linear(n_embd, head_size)

        #since this is a decoder, we need to initialize the mask as well

        #we register this as a buffer, which still exists as a 'matrix' to use, but we don't compute gradients on this or use in the backward pass
        #model parameters are objects that we use during the forward pass and we update using gradient descent
        #model buffers are objects that we use during computation but do not update

        #both parameters and buffers are saved to the right device when calling .to_device
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        #assume x is of shape (B, T, C)
        B, T, C = x.shape
        K = self.Wk(x) #(B, T, head_size)
        Q = self.Wq(x) #(B, T, head_size)
        V = self.Wv(x) #(B, T, head_size)

        #K.T needs to be of shape (B, C, T), so we swap the -2 and -1 positions
        scores = Q @ K.transpose(-2, -1) * 1/(self.head_size)**2 #(B, T, T)
        masked_scores = scores.masked_fill(self.tril[:T, :T] == 0, float('-inf')) #(B, T, T)
        attention_scores = F.softmax(masked_scores, dim = -1) #applying softmax along the rows (B, T, T)
        attention_scores = self.dropout(attention_scores) #(B, T, T)
        out = attention_scores @ V #(B, T, head_size)
        
        return out #(B, T, head_size)


In [85]:
class MultiHeadAttention(nn.Module):
    def __init__(self, n_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(n_heads)]) #(B, T, n_heads*head_size)
        self.proj = nn.Linear(n_heads * head_size, n_embd) #paper specifies a final linear layer
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        #assume input x is of size (B, T, C)

        #Each Head returns a output of size (B, T, head_size), we concatenate along the final dimension so that our variable 'out' is now (B, T, n_heads*head_size)
        out = torch.cat([h(x) for h in self.heads], dim = -1) #(B, T, n_heads*head_size)
        out = self.proj(out) #(B, T, C)
        out = self.dropout(out)

        return out

In [13]:
class FeedForward(nn.Module):
    def __init__(self):
        #input and output will be of size (B, T, C)
        self.ff1 = nn.Linear(n_embd, 4*n_embd)
        self.ff2 = nn.Linear(4*n_embd, n_embd)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        #assume x is of shape (B, T, C)
        x = self.ff1(x)
        x = self.relu(x)
        x = self.ff2(x)
        x = dropout(x)

        return x

In [14]:
class Block(nn.Module):
    #implementaion of one transformer block
    def __init__(self, n_head):
        super().__init__()
        self.head_size = n_embd / n_head

        self.sa = MultiHeadAttention(n_head, self.head_size)
        self.ffw = FeedForward(n_embd)
        self.layernorm1 = nn.LayerNorm(n_embd)
        self.layernorm2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        #assume input of x is size (B, T, C) where x is the sum of the embedded input + positional_encoding
        x = self.layernorm1(x) #(B, T, C)
        x = x + self.sa(x) #(B, T, C)
        x = self.layernorm2(x) #(B, T, C)
        x = x + self.ffw(x) #(B, T, C)

        return x


In [20]:
class Decoder(nn.Module):
    def __init__(self, n_blocks, n_heads):
        super().__init__()
        self.tok_embedding_matrix = nn.Embedding(vocab_size, n_embd)
        self.pos_embedding = nn.Embedding(block_size, n_embd)

        self.blocks = nn.Sequential([Block(n_heads) for _ in n_blocks])

        self.final_layer_norm = nn.LayerNorm(n_embd)
        self.final_linear = nn.Linear(n_embd, vocab_size)

    def forward(self, x, y):
        B, T, C, = x.shape
        #assume our inputs x are of size (B, T)
        #assume our targets y are of size (B)
        token_embed = self.tok_embedding_matrix(x)
        pos_embed = self.pos_embedding(x)

        input = token_embed + pos_embed
        input = self.blocks(input)

        input = self.final_layer_norm(input)
        logits = self.final_linear(input)

        logits = logits.view(B*T, -1)

        if y:
            loss = F.cross_entropy(logits, y)
        else:
            loss = None

        return logits, loss
        
        

rough work

In [80]:
tokens = nn.Embedding(vocab_size, n_embd)

xb = tokens(xb)

In [83]:
H = MultiHeadAttention(2, 16)
H = Head(16)

H(xb)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5003, 0.4997, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3348, 0.3322, 0.3330, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2492, 0.2510, 0.2496, 0.2503, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1991, 0.1999, 0.2016, 0.2005, 0.1989, 0.0000, 0.0000, 0.0000],
        [0.1666, 0.1664, 0.1666, 0.1663, 0.1660, 0.1681, 0.0000, 0.0000],
        [0.1434, 0.1436, 0.1420, 0.1428, 0.1433, 0.1431, 0.1419, 0.0000],
        [0.1251, 0.1250, 0.1250, 0.1247, 0.1249, 0.1253, 0.1249, 0.1250]],
       grad_fn=<SelectBackward0>)
tensor([[-0.0273,  0.9228,  0.0360,  0.1456,  0.6187, -0.0846, -1.0352,  0.0662,
          0.2726, -0.2818,  1.1334,  0.2416, -0.7980, -0.2744, -0.6682, -0.8704],
        [-0.2197,  0.0495, -0.1741,  0.7288,  0.2270,  0.3235,  0.9681,  0.8418,
          1.7442, -0.3903, -0.4830, -0.3293,  0.0269,  0.3564, -0.5448,  0.5546],
        [ 0.5079,  0.9698, -0.8998, -0.5712, -0

tensor([[[-2.7323e-02,  9.2276e-01,  3.6048e-02,  1.4556e-01,  6.1869e-01,
          -8.4573e-02, -1.0352e+00,  6.6203e-02,  2.7262e-01, -2.8181e-01,
           1.1334e+00,  2.4156e-01, -7.9797e-01, -2.7442e-01, -6.6818e-01,
          -8.7045e-01],
         [-1.2348e-01,  4.8636e-01, -6.8990e-02,  4.3702e-01,  4.2295e-01,
           1.1937e-01, -3.4105e-02,  4.5382e-01,  1.0080e+00, -3.3605e-01,
           3.2560e-01, -4.3730e-02, -3.8574e-01,  4.0809e-02, -6.0651e-01,
          -1.5832e-01],
         [ 8.6963e-02,  6.4830e-01, -3.4540e-01,  1.0065e-01,  1.5526e-01,
          -1.1321e-02,  2.9588e-01,  4.8785e-01,  7.7409e-01, -2.9125e-01,
           6.7575e-02, -4.8841e-01,  4.8466e-02,  3.6290e-02, -5.1983e-01,
           1.6180e-01],
         [ 2.2114e-01,  3.7889e-01, -4.1342e-01,  1.5419e-01,  6.6952e-02,
           7.3688e-02,  4.0018e-01,  2.8017e-01,  7.6637e-01, -5.8014e-02,
           2.9604e-01, -5.3323e-01, -1.1896e-01,  2.4816e-01, -5.1502e-01,
           7.0441e-02],
    